BadyetBuddy_prototype/app/models.py
from . import db
from datetime import datetime

class Badyet_Items(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(120))
    description = db.Column(db.String(200))
    category = db.Column(db.String(90))
    length = db.Column(db.String(90))
    amount = db.Column(db.Float)
    owner_id = db.Column(db.Integer)

class Badyet_Users(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(120))
    email = db.Column(db.String(200))
    password = db.Column(db.String(120))
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

BadyetBuddy_prototype/app.py
from app import create_app

app = create_app()

if __name__ == '__main__':
    app.run(debug=True)

BadyetBuddy_prototype/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import Config

db = SQLAlchemy()

def create_app():
    app = Flask(__name__, template_folder='../templates', static_folder='../static')
    app.config.from_object(Config)

    db.init_app(app)

    from .routes import main as main_blueprint
    app.register_blueprint(main_blueprint)

    with app.app_context():
        db.create_all()

    return app

BadyetBuddy_prototype/app/routes.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for
from .models import Badyet_Items
from . import db
from .util import query_helper

import sqlite3

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('index.html', page="home")

@main.route('/about')
def about():
    return render_template('about.html', page="about")

@main.route('/items', methods=['GET'])
def get_items():
    b_items = Badyet_Items.query.all()
    return jsonify(query_helper.get_all_items())

@main.route('/dashboard')
def dashboard():
    a_items = Badyet_Items.query.filter_by(category='income').all()
    incomes = [
        {
            'id': item.id,
            'name': item.name,
            'description': item.description,
            'category': item.category,
            'length': item.length,
            'amount': item.amount,
            'owner_id': item.owner_id
        } for item in a_items
    ]
    a_total = query_helper.get_sum("income")

    b_items = Badyet_Items.query.filter_by(category='expense').all()
    expenses = [
        {
            'id': item.id,
            'name': item.name,
            'description': item.description,
            'category': item.category,
            'length': item.length,
            'amount': item.amount,
            'owner_id': item.owner_id
        } for item in b_items
    ]
    b_total = query_helper.get_sum("expense")

    return render_template('dashboard.html', incomes=incomes, expenses=expenses, incm_total=a_total, expn_total=b_total, page="dashb")

@main.route('/incomes')
def incomes():
    b_items = Badyet_Items.query.filter_by(category='income').all()
    incomes = [
        {
            'id': item.id,
            'name': item.name,
            'description': item.description,
            'category': item.category,
            'length': item.length,
            'amount': item.amount,
            'owner_id': item.owner_id
        } for item in b_items
    ]
    return render_template('incomes.html', incomes=incomes)

@main.route('/expenses')
def expenses():
    b_items = Badyet_Items.query.filter_by(category='expense').all()
    expenses = [
        {
            'id': item.id,
            'name': item.name,
            'description': item.description,
            'category': item.category,
            'length': item.length,
            'amount': item.amount,
            'owner_id': item.owner_id
        } for item in b_items
    ]
    return render_template('expenses.html', expenses=expenses)

@main.route('/add', methods=["POST"])
def add_record():
    name = request.form.get("name")
    description = request.form.get("description")
    category = request.form.get("category")
    length = request.form.get("length")
    amount = request.form.get("amount")
    owner_id = request.form.get("owner_id")
    
    pg_name = request.form.get("pg_name")

    if name and description and category and length and amount and owner_id:
        new_record = Badyet_Items(name=name, description=description, category=category, length=length, amount=float(amount), owner_id=owner_id)
        db.session.add(new_record)
        db.session.commit()
        return redirect(url_for(f"main.{pg_name}"))
    return "Failed to add record. Ensure all fields are filled in."


@main.route("/edit/<int:id>", methods=["GET", "POST"])
def edit_record(id):
    record = Badyet_Items.query.get_or_404(id)
    if request.method == "POST":
        record.name = request.form.get("name")
        record.description = request.form.get("description")
        record.category = request.form.get("category")
        record.length = request.form.get("length")
        record.amount = request.form.get("amount")

        db.session.commit()
        return redirect(url_for("main.dashboard"))
    return render_template("edit.html", record=record)


@main.route("/delete/<int:id>", methods=["POST"])
def delete_record(id):
    record = Badyet_Items.query.get_or_404(id)
    db.session.delete(record)
    db.session.commit()
    return redirect(url_for("main.dashboard"))

BadyetBuddy_prototype/templates/about.html
{% extends "base.html" %}

{% block title %}About - My Flask App{% endblock %}

{% block content %}
<div class="parent">
    <div class="upper_left">

    </div>
    <div class="bottom_left">

    </div>
    <div class="top_main">
        
    </div>
    <div class="main">
        <h1>About Us</h1>
        <p>This is the about page.</p>
    </div>
    <div class="upper_right">

    </div>
    <div class="bottom_right">

    </div>
</div>
{% endblock %}

BadyetBuddy_prototype/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}BadyetBud{% endblock %}</title>
	<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<a class="navbar-brand" href="#">BDYTBD</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
				
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item {% if page == 'home' %}active{% endif %}">
						<a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
					</li>
					<li class="nav-item {% if page == 'dashb' %}active{% endif %}">
						<a class="nav-link" href="{{ url_for('main.dashboard') }}">BadyetBuddy</a>
					</li>
					<li class="nav-item {% if page == 'about' %}active{% endif %}">
						<a class="nav-link" href="{{ url_for('main.about') }}">About</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
							aria-haspopup="true" aria-expanded="false">
							Dropdown
						</a>
						<div class="dropdown-menu" aria-labelledby="navbarDropdown">
							<a class="dropdown-item" href="#">Action</a>
							<a class="dropdown-item" href="#">Another action</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Something else here</a>
						</div>
					</li>
					<li class="nav-item">
						<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
					</li>
				</ul>
				<form class="form-inline my-2 my-lg-0">
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>
			</div>
		</nav>
	</header>
	<main>
		<br>
		{% block content %}{% endblock %}
		<br>
	</main>
	<footer>
		<center>
			<p>&copy; 2025 My Flask App</p>
		</center>
	</footer>

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
		integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
		crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
		integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
		crossorigin="anonymous"></script>
</body>

</html>

BadyetBuddy_prototype/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Home - My Flask App{% endblock %}

{% block content %}
<div class="parent">
    <div class="upper_left">
        ads
    </div>
    <div class="bottom_left">
        ads
    </div>
    <div class="top_main">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('main.dashboard') }}">DashBoard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.incomes') }}">Incomes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.expenses') }}">Expenses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Savings</a>
            </li>
        </ul>
    </div>
    <div class="main">
        <!-- Main-->
        <h1>Income: {{incm_total}}</h1>
        {% for item in incomes %}
        <div class="alert alert-success" role="alert">
            <h2>P{{ item.amount }}</h2> {{ item.name }} - {{ item.description }} <a href="{{ url_for('main.edit_record', id=item.id) }}" class="alert-link">Edit</a>
            <form method="POST" action="{{ url_for('main.delete_record', id=item.id) }}" style="display:inline;">
                <button type="submit" onclick="return confirm('Are you sure you want to delete this record?');">Delete</button>
            </form>
        </div>
        {% endfor %}
        <br>
        <h1>Expenses: {{expn_total}}</h1>
        {% for item in expenses %}
        <div class="alert alert-warning" role="alert">
            <h2>P{{ item.amount }}</h2> {{ item.name }} - {{ item.description }} <a href="{{ url_for('main.edit_record', id=item.id) }}" class="alert-link">Edit</a>
            <form method="POST" action="{{ url_for('main.delete_record', id=item.id) }}" style="display:inline;">
                <button type="submit" onclick="return confirm('Are you sure you want to delete this record?');">Delete</button>
            </form>
        </div>
        {% endfor %}
    </div>
    <div class="upper_right">
        ads
    </div>
    <div class="bottom_right">
        ads
    </div>
</div>
<script>
    $(function () {
        $('[data-toggle="popover"]').popover()
    })
</script>

{% endblock %}

BadyetBuddy_prototype/templates/edit.html
{% extends "base.html" %}

{% block title %}Home - My Flask App{% endblock %}

{% block content %}

<div class="parent">
    <div class="upper_left">
        ads
    </div>
    <div class="bottom_left">
        ads
    </div>
    <div class="top_main">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.dashboard') }}">DashBoard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.incomes') }}">Incomes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.expenses') }}">Expenses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Savings</a>
            </li>
        </ul>
    </div>
    <div class="main">
        <!-- Main-->
        <h1>Edit Record</h1>
        <form method="POST" action="">
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" value="{{ record.name }}" required><br><br>
    
            <label for="description">Description:</label>
            <input type="text" id="description" name="description" value="{{ record.description }}" required><br><br>
    
            <label for="amount">Amount:</label>
            <input type="number" id="amount" name="amount" value="{{ record.amount }}" required><br><br>
            
            <label for="category">Category:</label>
            <select id="category" name="category" required>
                <option value="expense" {% if record.category == 'expense' %}selected{% endif %}>Expense</option>
                <option value="income" {% if record.category == 'income' %}selected{% endif %}>Income</option>
            </select><br><br>

            <label for="length">Length:</label>
            <select id="length" name="length" required>
                <option value="monthly" selected>Monthly</option>
                <option value="bimonthly" disabled>Bimonthly</option>
                <option value="weekly" disabled>Weekly</option>
            </select><br><br>
    
            <button type="submit">Update</button>
            <a href="{{ url_for('main.dashboard') }}">
                <button type="button">Cancel</button>
            </a>
        </form>
    </div>
    <div class="upper_right">
        ads
    </div>
    <div class="bottom_right">
        ads
    </div>
</div>
{% endblock %}

BadyetBuddy_prototype/templates/expenses.html
{% extends "base.html" %}

{% block title %}Home - My Flask App{% endblock %}

{% block content %}

<div class="parent">
    <div class="upper_left">
        ads
    </div>
    <div class="bottom_left">
        ads
    </div>
    <div class="top_main">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.dashboard') }}">DashBoard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.incomes') }}">Incomes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('main.expenses') }}">Expenses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Savings</a>
            </li>
        </ul>
    </div>
    <div class="main">
        <!-- Main-->
        <h1>Items List</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Category</th>
                    <th>Length</th>
                    <th>Amount</th>
                    <th>Owner ID</th>
                </tr>
            </thead>
            <tbody>
                {% for item in expenses %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.category }}</td>
                    <td>{{ item.length }}</td>
                    <td>{{ item.amount }}</td>
                    <td>{{ item.owner_id }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="upper_right">
        ads
    </div>
    <div class="bottom_right">
        ads
    </div>
</div>
{% endblock %}

BadyetBuddy_prototype/templates/incomes.html
{% extends "base.html" %}

{% block title %}Home - My Flask App{% endblock %}

{% block content %}
<div class="parent">
    <div class="upper_left">
        ads
    </div>
    <div class="bottom_left">
        ads
    </div>
    <div class="top_main">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.dashboard') }}">DashBoard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('main.incomes') }}">Incomes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.expenses') }}">Expenses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Savings</a>
            </li>
        </ul>
    </div>
    <div class="main">
        <!-- Main-->
        <h1>Items List</h1>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Category</th>
                    <th>Length</th>
                    <th>Amount</th>
                    <th>Owner ID</th>
                </tr>
            </thead>
            <tbody>
                {% for item in incomes %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.category }}</td>
                    <td>{{ item.length }}</td>
                    <td>{{ item.amount }}</td>
                    <td>{{ item.owner_id }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <h1>Create a New Record</h1>
        <form method="POST" action="/add">
            <input type="text" id="pg_name" name="pg_name" value="incomes" hidden>
            <input type="text" id="owner_id" name="owner_id" value="1" hidden>

            <label for="name">Name:</label>
            <input type="text" id="name" name="name" required><br><br>
    
            <label for="description">Description:</label>
            <input type="text" id="description" name="description" required><br><br>
    
            <label for="amount">Amount:</label>
            <input type="number" id="amount" name="amount" required><br><br>
            
            <label for="category">Category:</label>
            <select id="category" name="category" required>
                <option value="income" selected>Income</option>
                <option value="expense">Expense</option>
            </select><br><br>

            <label for="length">Length:</label>
            <select id="length" name="length" required>
                <option value="monthly" selected>Monthly</option>
                <option value="bimonthly" disabled>Bimonthly</option>
                <option value="weekly" disabled>Weekly</option>
            </select><br><br>


            <button type="submit">Submit</button>
        </form>
    </div>
    <div class="upper_right">
        ads
    </div>
    <div class="bottom_right">
        ads
    </div>
</div>
{% endblock %}

BadyetBuddy_prototype/templates/index.html
{% extends "base.html" %}

{% block title %}Home - My Flask App{% endblock %}

{% block content %}

<div class="parent">
    <div class="upper_left">
        ads
    </div>
    <div class="bottom_left">
        ads
    </div>
    <div class="top_main">
    </div>
    <div class="main">
        <!-- Main-->
        <center>
			<h2>Welcome to BadyetBuddy, your trusted companion for managing budgets and finances with ease and confidence. Let's embark on a journey towards financial freedom together!</h2>
		</center>
    </div>
    <div class="upper_right">
        ads
    </div>
    <div class="bottom_right">
        ads
    </div>
</div>
{% endblock %}